{"cmd":"taskkill /pid 6980 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill node: Command failed: taskkill /pid 6980 /T /F\nERROR: The process \"6980\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 6980 /T /F\nERROR: The process \"6980\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-20 22:04:29"}
{"cmd":"taskkill /pid 7480 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill node: Command failed: taskkill /pid 7480 /T /F\nERROR: The process \"7480\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 7480 /T /F\nERROR: The process \"7480\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-20 22:04:29"}
{"level":"error","message":"Backend Server stderr: node:internal/modules/cjs/loader:1252\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'validator'\r\nRequire stack:\r\n- C:\\Apps\\LazyEnder\\backend\\promptSender.js\r\n- C:\\Apps\\LazyEnder\\backend\\server.js\r\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)\r\n    at Function._load (node:internal/modules/cjs/loader:1075:27)\r\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)\r\n    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)\r\n    at Module.require (node:internal/modules/cjs/loader:1340:12)\r\n    at require (node:internal/modules/helpers:141:16)\r\n    at Object.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:4:19)\r\n    at Module._compile (node:internal/modules/cjs/loader:1546:14)\r\n    at Object..js (node:internal/modules/cjs/loader:1689:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1318:32) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: [\r\n    'C:\\\\Apps\\\\LazyEnder\\\\backend\\\\promptSender.js',\r\n    'C:\\\\Apps\\\\LazyEnder\\\\backend\\\\server.js'\r\n  ]\r\n}\r\n\r\nNode.js v22.11.0\r\n","service":"user-service","timestamp":"2024-11-22 22:03:05"}
{"cmd":"taskkill /pid 17548 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 17548 /T /F\nERROR: The process \"17548\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 17548 /T /F\nERROR: The process \"17548\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:03:28"}
{"level":"error","message":"Backend Server stderr: node:internal/modules/cjs/loader:1252\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'express-validator'\r\nRequire stack:\r\n- C:\\Apps\\LazyEnder\\backend\\server.js\r\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)\r\n    at Function._load (node:internal/modules/cjs/loader:1075:27)\r\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)\r\n    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)\r\n    at Module.require (node:internal/modules/cjs/loader:1340:12)\r\n    at require (node:internal/modules/helpers:141:16)\r\n    at Object.<anonymous> (C:\\Apps\\LazyEnder\\backend\\server.js:10:36)\r\n    at Module._compile (node:internal/modules/cjs/loader:1546:14)\r\n    at Object..js (node:internal/modules/cjs/loader:1689:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1318:32) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: [ 'C:\\\\Apps\\\\LazyEnder\\\\backend\\\\server.js' ]\r\n}\r\n\r\nNode.js v22.11.0\r\n","service":"user-service","timestamp":"2024-11-22 22:03:45"}
{"cmd":"taskkill /pid 20368 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 20368 /T /F\nERROR: The process \"20368\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 20368 /T /F\nERROR: The process \"20368\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:04:46"}
{"level":"error","message":"Backend Server stderr: node:internal/errors:540\r\n      throw error;\r\n      ^\r\n\r\nTypeError [ERR_INVALID_ARG_TYPE]: The \"listener\" argument must be of type function. Received an instance of Array\r\n    at checkListener (node:events:275:3)\r\n    at _addListener (node:events:551:3)\r\n    at Socket.addListener (node:events:610:10)\r\n    at Socket.on (C:\\Apps\\LazyEnder\\node_modules\\socket.io\\dist\\typed-events.js:26:22)\r\n    at Namespace.<anonymous> (C:\\Apps\\LazyEnder\\backend\\server.js:31:12)\r\n    at Namespace.emit (node:events:518:28)\r\n    at Namespace.emitReserved (C:\\Apps\\LazyEnder\\node_modules\\socket.io\\dist\\typed-events.js:56:22)\r\n    at Namespace._doConnect (C:\\Apps\\LazyEnder\\node_modules\\socket.io\\dist\\namespace.js:276:14)\r\n    at C:\\Apps\\LazyEnder\\node_modules\\socket.io\\dist\\namespace.js:238:22\r\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {\r\n  code: 'ERR_INVALID_ARG_TYPE'\r\n}\r\n\r\nNode.js v22.11.0\r\n","service":"user-service","timestamp":"2024-11-22 22:07:27"}
{"cmd":"taskkill /pid 16728 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 16728 /T /F\nERROR: The process \"16728\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 16728 /T /F\nERROR: The process \"16728\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:08:06"}
{"cmd":"taskkill /pid 16256 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 16256 /T /F\nERROR: The process \"16256\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 16256 /T /F\nERROR: The process \"16256\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:15:36"}
{"cmd":"taskkill /pid 21412 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 21412 /T /F\nERROR: The process \"21412\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 21412 /T /F\nERROR: The process \"21412\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:15:36"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:16:26"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:16:26"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:16:27"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:16:27"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:16:27"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:16:27"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:16:32"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:16:32"}
{"cmd":"taskkill /pid 15944 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 15944 /T /F\nERROR: The process \"15944\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 15944 /T /F\nERROR: The process \"15944\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:16:36"}
{"cmd":"taskkill /pid 25472 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 25472 /T /F\nERROR: The process \"25472\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 25472 /T /F\nERROR: The process \"25472\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:16:36"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:23:17"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:23:17"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:23:18"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:23:18"}
{"cmd":"taskkill /pid 15568 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 15568 /T /F\nERROR: The process \"15568\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 15568 /T /F\nERROR: The process \"15568\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:23:23"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:23:55"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:23:55"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:23:56"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:23:56"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:23:56"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:23:56"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:23:56"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:23:56"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:23:58"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:23:58"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:24:02"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:24:02"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:24:15"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:24:15"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:24:16"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:24:16"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:24:16"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:24:16"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:25:59"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:25:59"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:26:00"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:26:00"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:26:00"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:26:00"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:26:01"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:26:01"}
{"cmd":"taskkill /pid 8716 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 8716 /T /F\nERROR: The process \"8716\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 8716 /T /F\nERROR: The process \"8716\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:26:18"}
{"cmd":"taskkill /pid 20836 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 20836 /T /F\nERROR: The process \"20836\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 20836 /T /F\nERROR: The process \"20836\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:26:18"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:29:12"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:29:12"}
{"cmd":"taskkill /pid 19088 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 19088 /T /F\nERROR: The process \"19088\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 19088 /T /F\nERROR: The process \"19088\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:29:34"}
{"cmd":"taskkill /pid 13080 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 13080 /T /F\nERROR: The process \"13080\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 13080 /T /F\nERROR: The process \"13080\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:29:34"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:32:27"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:32:27"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: timeout\n","service":"user-service","timestamp":"2024-11-22 22:32:29"}
{"level":"error","message":"Error sending prompt: Connection error: timeout","service":"user-service","stack":"Error: Connection error: timeout\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:35:24)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at Socket.onerror (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\socket.js:457:18)\n    at Emitter.emit (C:\\Apps\\LazyEnder\\node_modules\\@socket.io\\component-emitter\\lib\\cjs\\index.js:143:20)\n    at onError (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:158:18)\n    at Timeout.<anonymous> (C:\\Apps\\LazyEnder\\node_modules\\socket.io-client\\build\\cjs\\manager.js:176:17)\n    at listOnTimeout (node:internal/timers:594:17)\n    at process.processTimers (node:internal/timers:529:7)","timestamp":"2024-11-22 22:32:29"}
{"cmd":"taskkill /pid 23356 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 23356 /T /F\nERROR: The process \"23356\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 23356 /T /F\nERROR: The process \"23356\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:36:10"}
{"cmd":"taskkill /pid 11644 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 11644 /T /F\nERROR: The process \"11644\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 11644 /T /F\nERROR: The process \"11644\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:36:10"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:38:57"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:38:57"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:39:02"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:39:02"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:39:03"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:39:03"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:39:04"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:39:04"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:39:30"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:39:30"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:39:30"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:39:30"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:39:31"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:39:31"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:39:35"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:34:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:39:35"}
{"cmd":"taskkill /pid 22004 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 22004 /T /F\nERROR: The process \"22004\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 22004 /T /F\nERROR: The process \"22004\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:42:22"}
{"cmd":"taskkill /pid 10444 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 10444 /T /F\nERROR: The process \"10444\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 10444 /T /F\nERROR: The process \"10444\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:42:22"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:42:56"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:58:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:42:56"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: read ECONNRESET\n","service":"user-service","timestamp":"2024-11-22 22:42:56"}
{"level":"error","message":"Error sending prompt: Connection error: read ECONNRESET","service":"user-service","stack":"Error: Connection error: read ECONNRESET\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:58:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:42:56"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:43:15"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:58:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:43:15"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:43:19"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:58:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:43:19"}
{"level":"error","message":"Error sending prompt: Connection error: read ECONNRESET","service":"user-service","stack":"Error: Connection error: read ECONNRESET\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:58:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:43:23"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: read ECONNRESET\n","service":"user-service","timestamp":"2024-11-22 22:43:23"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:43:30"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:58:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:43:30"}
{"level":"error","message":"Error sending prompt: Connection error: read ECONNRESET","service":"user-service","stack":"Error: Connection error: read ECONNRESET\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:58:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:44:02"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: read ECONNRESET\n","service":"user-service","timestamp":"2024-11-22 22:44:02"}
{"cmd":"taskkill /pid 14444 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 14444 /T /F\nERROR: The process \"14444\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 14444 /T /F\nERROR: The process \"14444\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:47:49"}
{"cmd":"taskkill /pid 19576 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 19576 /T /F\nERROR: The process \"19576\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 19576 /T /F\nERROR: The process \"19576\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at Socket.<anonymous> (node:internal/child_process:456:11)\n    at Socket.emit (node:events:518:28)\n    at Pipe.<anonymous> (node:net:343:12)","timestamp":"2024-11-22 22:47:49"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:48:18"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:63:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:48:18"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:63:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:48:39"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:48:39"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:48:45"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:63:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:48:45"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:63:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:48:47"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:48:47"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:49:06"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:63:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:49:06"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:49:14"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:63:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:49:14"}
{"cmd":"taskkill /pid 6344 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 6344 /T /F\nERROR: The process \"6344\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 6344 /T /F\nERROR: The process \"6344\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:50:48"}
{"cmd":"taskkill /pid 22896 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 22896 /T /F\nERROR: The process \"22896\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 22896 /T /F\nERROR: The process \"22896\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:50:48"}
{"level":"error","message":"Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001\n","service":"user-service","timestamp":"2024-11-22 22:51:26"}
{"level":"error","message":"Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001","service":"user-service","stack":"Error: Connection error: connect ETIMEDOUT 25.28.81.126:5001\n    at Socket.<anonymous> (C:\\Apps\\LazyEnder\\backend\\promptSender.js:62:24)\n    at Socket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2024-11-22 22:51:26"}
{"cmd":"taskkill /pid 8696 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 8696 /T /F\nERROR: The process \"8696\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 8696 /T /F\nERROR: The process \"8696\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:59:47"}
{"cmd":"taskkill /pid 10232 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 10232 /T /F\nERROR: The process \"10232\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 10232 /T /F\nERROR: The process \"10232\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 22:59:47"}
{"cmd":"taskkill /pid 19736 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 19736 /T /F\nERROR: The process \"19736\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 19736 /T /F\nERROR: The process \"19736\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at Socket.<anonymous> (node:internal/child_process:456:11)\n    at Socket.emit (node:events:518:28)\n    at Pipe.<anonymous> (node:net:343:12)","timestamp":"2024-11-22 23:04:23"}
{"cmd":"taskkill /pid 8252 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 8252 /T /F\nERROR: The process \"8252\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 8252 /T /F\nERROR: The process \"8252\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:04:23"}
{"cmd":"taskkill /pid 14200 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 14200 /T /F\nERROR: The process \"14200\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 14200 /T /F\nERROR: The process \"14200\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:12:43"}
{"cmd":"taskkill /pid 6960 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 6960 /T /F\nERROR: The process \"6960\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 6960 /T /F\nERROR: The process \"6960\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:12:43"}
{"level":"error","message":"Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at node:net:2170:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\n  code: 'EADDRINUSE',\n  errno: -4091,\n  syscall: 'listen',\n  address: '25.39.138.224',\n  port: 5000\n}\n","service":"user-service","timestamp":"2024-11-22 23:12:48"}
{"cmd":"taskkill /pid 5728 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 5728 /T /F\nERROR: The process \"5728\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 5728 /T /F\nERROR: The process \"5728\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:14:25"}
{"cmd":"taskkill /pid 20472 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 20472 /T /F\nERROR: The process \"20472\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 20472 /T /F\nERROR: The process \"20472\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:14:25"}
{"level":"error","message":"Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at node:net:2170:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\n  code: 'EADDRINUSE',\n  errno: -4091,\n  syscall: 'listen',\n  address: '25.39.138.224',\n  port: 5000\n}\n","service":"user-service","timestamp":"2024-11-22 23:14:29"}
{"cmd":"taskkill /pid 4996 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 4996 /T /F\nERROR: The process \"4996\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 4996 /T /F\nERROR: The process \"4996\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:17:49"}
{"cmd":"taskkill /pid 7944 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 7944 /T /F\nERROR: The process \"7944\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 7944 /T /F\nERROR: The process \"7944\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:17:49"}
{"level":"error","message":"Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at node:net:2170:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\n  code: 'EADDRINUSE',\n  errno: -4091,\n  syscall: 'listen',\n  address: '25.39.138.224',\n  port: 5000\n}\n","service":"user-service","timestamp":"2024-11-22 23:17:53"}
{"cmd":"taskkill /pid 20372 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 20372 /T /F\nERROR: The process \"20372\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 20372 /T /F\nERROR: The process \"20372\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:22:40"}
{"cmd":"taskkill /pid 6472 /T /F","code":128,"killed":false,"level":"error","message":"Failed to kill Backend Server: Command failed: taskkill /pid 6472 /T /F\nERROR: The process \"6472\" not found.\r\n","service":"user-service","signal":null,"stack":"Error: Command failed: taskkill /pid 6472 /T /F\nERROR: The process \"6472\" not found.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:419:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1104:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","timestamp":"2024-11-22 23:22:40"}
{"level":"error","message":"Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at node:net:2170:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\n  code: 'EADDRINUSE',\n  errno: -4091,\n  syscall: 'listen',\n  address: '25.39.138.224',\n  port: 5000\n}\n","service":"user-service","timestamp":"2024-11-22 23:22:43"}
{"level":"error","message":"Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at node:net:2170:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\n  code: 'EADDRINUSE',\n  errno: -4091,\n  syscall: 'listen',\n  address: '25.39.138.224',\n  port: 5000\n}\n","service":"user-service","timestamp":"2024-11-22 23:27:28"}
{"level":"error","message":"Failed to kill Receive Image Server: Command failed: taskkill /pid 4548 /T /F\nERROR: The process \"4548\" not found.\r\n","service":"user-service","timestamp":"2024-11-22 23:27:30"}
{"level":"error","message":"Receive Image Server stderr: node:internal/modules/cjs/loader:1252\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'uuid'\r\nRequire stack:\r\n- C:\\Apps\\LazyEnder\\backend\\receiveImage.js\r\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)\r\n    at Function._load (node:internal/modules/cjs/loader:1075:27)\r\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)\r\n    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)\r\n    at Module.require (node:internal/modules/cjs/loader:1340:12)\r\n    at require (node:internal/modules/helpers:141:16)\r\n    at Object.<anonymous> (C:\\Apps\\LazyEnder\\backend\\receiveImage.js:7:24)\r\n    at Module._compile (node:internal/modules/cjs/loader:1546:14)\r\n    at Object..js (node:internal/modules/cjs/loader:1689:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1318:32) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: [ 'C:\\\\Apps\\\\LazyEnder\\\\backend\\\\receiveImage.js' ]\r\n}\r\n\r\nNode.js v22.11.0\r\n","service":"user-service","timestamp":"2024-11-22 23:46:33"}
{"level":"error","message":"Backend Server stderr: node:internal/modules/cjs/loader:1252\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'uuid'\r\nRequire stack:\r\n- C:\\Apps\\LazyEnder\\backend\\receiveImage.js\r\n- C:\\Apps\\LazyEnder\\backend\\server.js\r\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)\r\n    at Function._load (node:internal/modules/cjs/loader:1075:27)\r\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)\r\n    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)\r\n    at Module.require (node:internal/modules/cjs/loader:1340:12)\r\n    at require (node:internal/modules/helpers:141:16)\r\n    at Object.<anonymous> (C:\\Apps\\LazyEnder\\backend\\receiveImage.js:7:24)\r\n    at Module._compile (node:internal/modules/cjs/loader:1546:14)\r\n    at Object..js (node:internal/modules/cjs/loader:1689:10)\r\n    at Module.load (node:internal/modules/cjs/loader:1318:32) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: [\r\n    'C:\\\\Apps\\\\LazyEnder\\\\backend\\\\receiveImage.js',\r\n    'C:\\\\Apps\\\\LazyEnder\\\\backend\\\\server.js'\r\n  ]\r\n}\r\n\r\nNode.js v22.11.0\r\n","service":"user-service","timestamp":"2024-11-22 23:46:33"}
{"level":"error","message":"Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at node:net:2170:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\n  code: 'EADDRINUSE',\n  errno: -4091,\n  syscall: 'listen',\n  address: '25.39.138.224',\n  port: 5000\n}\n","service":"user-service","timestamp":"2024-11-22 23:46:54"}
{"level":"error","message":"Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1907:16)\n    at listenInCluster (node:net:1964:12)\n    at node:net:2170:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {\n  code: 'EADDRINUSE',\n  errno: -4091,\n  syscall: 'listen',\n  address: '25.39.138.224',\n  port: 5000\n}\n","service":"user-service","timestamp":"2024-11-23 09:39:38"}
{"0":"E","1":"R","10":" ","11":"p","12":"r","13":"o","14":"c","15":"e","16":"s","17":"s","18":" ","19":"\"","2":"R","20":"1","21":"8","22":"0","23":"1","24":"2","25":"\"","26":" ","27":"n","28":"o","29":"t","3":"O","30":" ","31":"f","32":"o","33":"u","34":"n","35":"d","36":".","37":"\r","38":"\n","4":"R","5":":","6":" ","7":"T","8":"h","9":"e","level":"error","message":"Failed to kill Backend Server with taskkill:","service":"user-service","timestamp":"2024-11-23 09:54:39"}
2024-11-23 10:07:31 [user-service] error: Backend Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at node:net:2170:7
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '25.39.138.224',
  port: 5000
}

2024-11-23 10:20:32 [user-service] error: Receive Image Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at node:net:2170:7
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '25.39.138.224',
  port: 5000
}

2024-11-23 10:20:32 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at Object.<anonymous> (C:\Apps\LazyEnder\backend\server.js:71:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 10:28:11 [user-service] error: Receive Image Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at node:net:2170:7
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '25.39.138.224',
  port: 5000
}

2024-11-23 10:28:11 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at Object.<anonymous> (C:\Apps\LazyEnder\backend\server.js:71:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 10:30:23 [user-service] error: Receive Image Server stderr: Error starting the server: Error: listen EADDRINUSE: address already in use 25.39.138.224:5000
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at node:net:2170:7
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '25.39.138.224',
  port: 5000
}

2024-11-23 10:30:24 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at Object.<anonymous> (C:\Apps\LazyEnder\backend\server.js:71:8)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 10:46:29 [user-service] error: Receive Image Server stderr: node:internal/modules/esm/resolve:257
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Apps\LazyEnder\backend\config\settings' imported from C:\Apps\LazyEnder\backend\receiveImage.js
    at finalizeResolution (node:internal/modules/esm/resolve:257:11)
    at moduleResolve (node:internal/modules/esm/resolve:913:10)
    at defaultResolve (node:internal/modules/esm/resolve:1037:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:582:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:132:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Apps/LazyEnder/backend/config/settings'
}

Node.js v22.11.0

2024-11-23 10:46:29 [user-service] error: Backend Server stderr: node:internal/modules/esm/resolve:257
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Apps\LazyEnder\backend\promptSender' imported from C:\Apps\LazyEnder\backend\server.js
    at finalizeResolution (node:internal/modules/esm/resolve:257:11)
    at moduleResolve (node:internal/modules/esm/resolve:913:10)
    at defaultResolve (node:internal/modules/esm/resolve:1037:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:582:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:132:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Apps/LazyEnder/backend/promptSender'
}

Node.js v22.11.0

2024-11-23 10:48:00 [user-service] error: Receive Image Server stderr: file:///C:/Apps/LazyEnder/backend/receiveImage.js:8
import settings from './config/settings.js';
       ^^^^^^^^
SyntaxError: The requested module './config/settings.js' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0

2024-11-23 10:48:00 [user-service] error: Backend Server stderr: file:///C:/Apps/LazyEnder/backend/receiveImage.js:8
import settings from './config/settings.js';
       ^^^^^^^^
SyntaxError: The requested module './config/settings.js' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0

2024-11-23 10:49:55 [user-service] error: Backend Server stderr: file:///C:/Apps/LazyEnder/backend/server.js:10
import errorHandler from './middleware/errorHandler.js';
       ^^^^^^^^^^^^
SyntaxError: The requested module './middleware/errorHandler.js' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0

2024-11-23 10:49:55 [user-service] error: Error starting the server: WebSocket.Server is not a constructor
2024-11-23 10:51:13 [user-service] error: Backend Server stderr: file:///C:/Apps/LazyEnder/backend/server.js:8
import sendPromptToFriend from './promptSender.js';
       ^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module './promptSender.js' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0

2024-11-23 10:51:13 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 10:52:58 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 10:52:59 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at file:///C:/Apps/LazyEnder/backend/server.js:74:8
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 10:56:00 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 10:56:00 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at startServer (file:///C:/Apps/LazyEnder/backend/server.js:81:12)
    at file:///C:/Apps/LazyEnder/backend/server.js:96:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 10:57:23 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 10:57:23 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at startServer (file:///C:/Apps/LazyEnder/backend/server.js:81:12)
    at file:///C:/Apps/LazyEnder/backend/server.js:96:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 10:59:32 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 10:59:33 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at startServer (file:///C:/Apps/LazyEnder/backend/server.js:81:12)
    at file:///C:/Apps/LazyEnder/backend/server.js:96:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 11:01:19 [user-service] error: Address in use, retrying with a different port...
2024-11-23 11:01:19 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at startServer (file:///C:/Apps/LazyEnder/backend/server.js:81:12)
    at file:///C:/Apps/LazyEnder/backend/server.js:103:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 11:01:40 [user-service] error: Address in use, retrying with a different port...
2024-11-23 11:01:41 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at startServer (file:///C:/Apps/LazyEnder/backend/server.js:81:12)
    at file:///C:/Apps/LazyEnder/backend/server.js:103:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 11:03:28 [user-service] error: Address in use, retrying with a different port...
2024-11-23 11:03:28 [user-service] error: Backend Server stderr: node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1907:16)
    at listenInCluster (node:net:1964:12)
    at Server.listen (node:net:2066:7)
    at startServer (file:///C:/Apps/LazyEnder/backend/server.js:81:12)
    at file:///C:/Apps/LazyEnder/backend/server.js:114:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1943:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.11.0

2024-11-23 11:06:01 [user-service] error: Address in use, retrying with a different port...
2024-11-23 11:06:02 [user-service] error: Address in use, retrying with a different port...
2024-11-23 11:08:29 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 11:08:30 [user-service] error: Backend Server stderr: file:///C:/Apps/LazyEnder/backend/server.js:37
    app.use('/static', express.static(path.join(__dirname, '../frontend/static')));
                                                ^

ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'C:\Apps\LazyEnder\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at startServer (file:///C:/Apps/LazyEnder/backend/server.js:37:49)
    at file:///C:/Apps/LazyEnder/backend/server.js:101:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0

2024-11-23 11:09:56 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 11:11:55 [user-service] error: Error starting the server: listen EADDRINUSE: address already in use 25.39.138.224:5000
2024-11-23 11:18:25 [user-service] error: Receive Image Server stderr: node:internal/modules/esm/resolve:838
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'portfinder' imported from C:\Apps\LazyEnder\backend\receiveImage.js
    at packageResolve (node:internal/modules/esm/resolve:838:9)
    at moduleResolve (node:internal/modules/esm/resolve:907:18)
    at defaultResolve (node:internal/modules/esm/resolve:1037:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:582:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:132:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.11.0

2024-11-23 11:18:25 [user-service] error: Backend Server stderr: node:internal/modules/esm/resolve:838
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'portfinder' imported from C:\Apps\LazyEnder\backend\server.js
    at packageResolve (node:internal/modules/esm/resolve:838:9)
    at moduleResolve (node:internal/modules/esm/resolve:907:18)
    at defaultResolve (node:internal/modules/esm/resolve:1037:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:650:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:599:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:582:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:241:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:132:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.11.0

2024-11-23 11:24:32 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001

2024-11-23 11:24:32 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001
2024-11-23 11:24:41 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5001
2024-11-23 11:24:41 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5001

2024-11-23 11:27:02 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:27:02 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:27:18 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:27:18 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:27:47 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:27:47 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:27:51 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:27:51 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:29:06 [user-service] error: Error stopping undefined: Command failed: taskkill /pid 9128 /T /F
ERROR: The process "9128" not found.

2024-11-23 11:31:18 [user-service] error: Error stopping undefined: Command failed: taskkill /pid 13056 /T /F
ERROR: The process "13056" not found.

2024-11-23 11:33:17 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:33:17 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:33:19 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:33:19 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:33:24 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:33:24 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:33:30 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:33:30 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:33:35 [user-service] error: Error sending prompt: Connection error: connect ETIMEDOUT 25.28.81.126:5002
2024-11-23 11:33:35 [user-service] error: Backend Server stderr: Failed to connect to friend: connect ETIMEDOUT 25.28.81.126:5002

2024-11-23 11:33:37 [user-service] error: Error stopping undefined: Command failed: taskkill /pid 11628 /T /F
ERROR: The process "11628" not found.

